// OWN

declare const enum QueueType {
  UNKNOWN = 'UNKNOWN',
  CUSTOM = 'CUSTOM',
  HA_NORMAL_ARAM = 'HA_NORMAL_ARAM',
  SR_SPECIAL_URF = 'SR_SPECIAL_URF',
  SR_SPECIAL_AR = 'SR_SPECIAL_AR',
  SR_SPECIAL_OFA = 'SR_SPECIAL_OFA',
  SR_NORMAL_CLASH = 'SR_NORMAL_CLASH',
  SR_NORMAL_DRAFT = 'SR_NORMAL_DRAFT',
  SR_NORMAL_BLIND = 'SR_NORMAL_BLIND',
  SR_RANKED_SOLO = 'SR_RANKED_SOLO',
  SR_RANKED_FLEX = 'SR_RANKED_FLEX',
  SR_TUTO_1 = 'SR_TUTO_1',
  SR_TUTO_2 = 'SR_TUTO_2',
  SR_TUTO_3 = 'SR_TUTO_3',
  TFT = 'TFT',
  TFT_RANKED = 'TFT_RANKED',
}
